// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pcd/v1/bluetooth.proto

package pcdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BluetoothDevice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias          string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Class          uint32                 `protobuf:"varint,4,opt,name=class,proto3" json:"class,omitempty"`
	BatteryPercent *int32                 `protobuf:"varint,5,opt,name=battery_percent,json=batteryPercent,proto3,oneof" json:"battery_percent,omitempty"`
	Rssi           *int32                 `protobuf:"varint,6,opt,name=rssi,proto3,oneof" json:"rssi,omitempty"`
	Connected      bool                   `protobuf:"varint,7,opt,name=connected,proto3" json:"connected,omitempty"`
	Paired         bool                   `protobuf:"varint,8,opt,name=paired,proto3" json:"paired,omitempty"`
	Trusted        bool                   `protobuf:"varint,9,opt,name=trusted,proto3" json:"trusted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BluetoothDevice) Reset() {
	*x = BluetoothDevice{}
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BluetoothDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BluetoothDevice) ProtoMessage() {}

func (x *BluetoothDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BluetoothDevice.ProtoReflect.Descriptor instead.
func (*BluetoothDevice) Descriptor() ([]byte, []int) {
	return file_pcd_v1_bluetooth_proto_rawDescGZIP(), []int{0}
}

func (x *BluetoothDevice) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BluetoothDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BluetoothDevice) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *BluetoothDevice) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *BluetoothDevice) GetBatteryPercent() int32 {
	if x != nil && x.BatteryPercent != nil {
		return *x.BatteryPercent
	}
	return 0
}

func (x *BluetoothDevice) GetRssi() int32 {
	if x != nil && x.Rssi != nil {
		return *x.Rssi
	}
	return 0
}

func (x *BluetoothDevice) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *BluetoothDevice) GetPaired() bool {
	if x != nil {
		return x.Paired
	}
	return false
}

func (x *BluetoothDevice) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

type BluetoothStatePayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventType        string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "connected", "disconnected", "updated", "snapshot"
	Device           *BluetoothDevice       `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`                        // The device that triggered the event (may be empty for snapshots)
	ConnectedDevices []*BluetoothDevice     `protobuf:"bytes,3,rep,name=connected_devices,json=connectedDevices,proto3" json:"connected_devices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BluetoothStatePayload) Reset() {
	*x = BluetoothStatePayload{}
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BluetoothStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BluetoothStatePayload) ProtoMessage() {}

func (x *BluetoothStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BluetoothStatePayload.ProtoReflect.Descriptor instead.
func (*BluetoothStatePayload) Descriptor() ([]byte, []int) {
	return file_pcd_v1_bluetooth_proto_rawDescGZIP(), []int{1}
}

func (x *BluetoothStatePayload) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BluetoothStatePayload) GetDevice() *BluetoothDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *BluetoothStatePayload) GetConnectedDevices() []*BluetoothDevice {
	if x != nil {
		return x.ConnectedDevices
	}
	return nil
}

type StreamBluetoothStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBluetoothStateRequest) Reset() {
	*x = StreamBluetoothStateRequest{}
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBluetoothStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBluetoothStateRequest) ProtoMessage() {}

func (x *StreamBluetoothStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBluetoothStateRequest.ProtoReflect.Descriptor instead.
func (*StreamBluetoothStateRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_bluetooth_proto_rawDescGZIP(), []int{2}
}

type StreamBluetoothStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       *BluetoothStatePayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBluetoothStateResponse) Reset() {
	*x = StreamBluetoothStateResponse{}
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBluetoothStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBluetoothStateResponse) ProtoMessage() {}

func (x *StreamBluetoothStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_bluetooth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBluetoothStateResponse.ProtoReflect.Descriptor instead.
func (*StreamBluetoothStateResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_bluetooth_proto_rawDescGZIP(), []int{3}
}

func (x *StreamBluetoothStateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamBluetoothStateResponse) GetPayload() *BluetoothStatePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pcd_v1_bluetooth_proto protoreflect.FileDescriptor

const file_pcd_v1_bluetooth_proto_rawDesc = "" +
	"\n" +
	"\x16pcd/v1/bluetooth.proto\x12\x06pcd.v1\"\x9f\x02\n" +
	"\x0fBluetoothDevice\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x14\n" +
	"\x05class\x18\x04 \x01(\rR\x05class\x12,\n" +
	"\x0fbattery_percent\x18\x05 \x01(\x05H\x00R\x0ebatteryPercent\x88\x01\x01\x12\x17\n" +
	"\x04rssi\x18\x06 \x01(\x05H\x01R\x04rssi\x88\x01\x01\x12\x1c\n" +
	"\tconnected\x18\a \x01(\bR\tconnected\x12\x16\n" +
	"\x06paired\x18\b \x01(\bR\x06paired\x12\x18\n" +
	"\atrusted\x18\t \x01(\bR\atrustedB\x12\n" +
	"\x10_battery_percentB\a\n" +
	"\x05_rssi\"\xad\x01\n" +
	"\x15BluetoothStatePayload\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12/\n" +
	"\x06device\x18\x02 \x01(\v2\x17.pcd.v1.BluetoothDeviceR\x06device\x12D\n" +
	"\x11connected_devices\x18\x03 \x03(\v2\x17.pcd.v1.BluetoothDeviceR\x10connectedDevices\"\x1d\n" +
	"\x1bStreamBluetoothStateRequest\"u\n" +
	"\x1cStreamBluetoothStateResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x127\n" +
	"\apayload\x18\x02 \x01(\v2\x1d.pcd.v1.BluetoothStatePayloadR\apayload2w\n" +
	"\x10BluetoothService\x12c\n" +
	"\x14StreamBluetoothState\x12#.pcd.v1.StreamBluetoothStateRequest\x1a$.pcd.v1.StreamBluetoothStateResponse0\x01B<Z:github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1;pcdv1b\x06proto3"

var (
	file_pcd_v1_bluetooth_proto_rawDescOnce sync.Once
	file_pcd_v1_bluetooth_proto_rawDescData []byte
)

func file_pcd_v1_bluetooth_proto_rawDescGZIP() []byte {
	file_pcd_v1_bluetooth_proto_rawDescOnce.Do(func() {
		file_pcd_v1_bluetooth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcd_v1_bluetooth_proto_rawDesc), len(file_pcd_v1_bluetooth_proto_rawDesc)))
	})
	return file_pcd_v1_bluetooth_proto_rawDescData
}

var file_pcd_v1_bluetooth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pcd_v1_bluetooth_proto_goTypes = []any{
	(*BluetoothDevice)(nil),              // 0: pcd.v1.BluetoothDevice
	(*BluetoothStatePayload)(nil),        // 1: pcd.v1.BluetoothStatePayload
	(*StreamBluetoothStateRequest)(nil),  // 2: pcd.v1.StreamBluetoothStateRequest
	(*StreamBluetoothStateResponse)(nil), // 3: pcd.v1.StreamBluetoothStateResponse
}
var file_pcd_v1_bluetooth_proto_depIdxs = []int32{
	0, // 0: pcd.v1.BluetoothStatePayload.device:type_name -> pcd.v1.BluetoothDevice
	0, // 1: pcd.v1.BluetoothStatePayload.connected_devices:type_name -> pcd.v1.BluetoothDevice
	1, // 2: pcd.v1.StreamBluetoothStateResponse.payload:type_name -> pcd.v1.BluetoothStatePayload
	2, // 3: pcd.v1.BluetoothService.StreamBluetoothState:input_type -> pcd.v1.StreamBluetoothStateRequest
	3, // 4: pcd.v1.BluetoothService.StreamBluetoothState:output_type -> pcd.v1.StreamBluetoothStateResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pcd_v1_bluetooth_proto_init() }
func file_pcd_v1_bluetooth_proto_init() {
	if File_pcd_v1_bluetooth_proto != nil {
		return
	}
	file_pcd_v1_bluetooth_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcd_v1_bluetooth_proto_rawDesc), len(file_pcd_v1_bluetooth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcd_v1_bluetooth_proto_goTypes,
		DependencyIndexes: file_pcd_v1_bluetooth_proto_depIdxs,
		MessageInfos:      file_pcd_v1_bluetooth_proto_msgTypes,
	}.Build()
	File_pcd_v1_bluetooth_proto = out.File
	file_pcd_v1_bluetooth_proto_goTypes = nil
	file_pcd_v1_bluetooth_proto_depIdxs = nil
}
