// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pcd/v1/media.proto

package pcdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaTrackMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TrackId            string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist             []string               `protobuf:"bytes,3,rep,name=artist,proto3" json:"artist,omitempty"`
	Album              string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	ArtUrl             string                 `protobuf:"bytes,5,opt,name=art_url,json=artUrl,proto3" json:"art_url,omitempty"`
	ArtRaw             []byte                 `protobuf:"bytes,6,opt,name=art_raw,json=artRaw,proto3" json:"art_raw,omitempty"` // Raw image byte data, avoiding Base64 encoding!
	LengthMicroseconds int64                  `protobuf:"varint,7,opt,name=length_microseconds,json=lengthMicroseconds,proto3" json:"length_microseconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MediaTrackMetadata) Reset() {
	*x = MediaTrackMetadata{}
	mi := &file_pcd_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaTrackMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaTrackMetadata) ProtoMessage() {}

func (x *MediaTrackMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaTrackMetadata.ProtoReflect.Descriptor instead.
func (*MediaTrackMetadata) Descriptor() ([]byte, []int) {
	return file_pcd_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaTrackMetadata) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaTrackMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MediaTrackMetadata) GetArtist() []string {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *MediaTrackMetadata) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *MediaTrackMetadata) GetArtUrl() string {
	if x != nil {
		return x.ArtUrl
	}
	return ""
}

func (x *MediaTrackMetadata) GetArtRaw() []byte {
	if x != nil {
		return x.ArtRaw
	}
	return nil
}

func (x *MediaTrackMetadata) GetLengthMicroseconds() int64 {
	if x != nil {
		return x.LengthMicroseconds
	}
	return 0
}

type MediaPlayerState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PlayerName           string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Identity             string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	DesktopEntry         string                 `protobuf:"bytes,3,opt,name=desktop_entry,json=desktopEntry,proto3" json:"desktop_entry,omitempty"`
	PlaybackStatus       string                 `protobuf:"bytes,4,opt,name=playback_status,json=playbackStatus,proto3" json:"playback_status,omitempty"` // "Playing", "Paused", "Stopped"
	Volume               float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	PositionMicroseconds int64                  `protobuf:"varint,6,opt,name=position_microseconds,json=positionMicroseconds,proto3" json:"position_microseconds,omitempty"`
	Metadata             *MediaTrackMetadata    `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaPlayerState) Reset() {
	*x = MediaPlayerState{}
	mi := &file_pcd_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaPlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaPlayerState) ProtoMessage() {}

func (x *MediaPlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaPlayerState.ProtoReflect.Descriptor instead.
func (*MediaPlayerState) Descriptor() ([]byte, []int) {
	return file_pcd_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaPlayerState) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *MediaPlayerState) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *MediaPlayerState) GetDesktopEntry() string {
	if x != nil {
		return x.DesktopEntry
	}
	return ""
}

func (x *MediaPlayerState) GetPlaybackStatus() string {
	if x != nil {
		return x.PlaybackStatus
	}
	return ""
}

func (x *MediaPlayerState) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MediaPlayerState) GetPositionMicroseconds() int64 {
	if x != nil {
		return x.PositionMicroseconds
	}
	return 0
}

func (x *MediaPlayerState) GetMetadata() *MediaTrackMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MediaStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivePlayers []*MediaPlayerState    `protobuf:"bytes,1,rep,name=active_players,json=activePlayers,proto3" json:"active_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaStatePayload) Reset() {
	*x = MediaStatePayload{}
	mi := &file_pcd_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStatePayload) ProtoMessage() {}

func (x *MediaStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaStatePayload.ProtoReflect.Descriptor instead.
func (*MediaStatePayload) Descriptor() ([]byte, []int) {
	return file_pcd_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *MediaStatePayload) GetActivePlayers() []*MediaPlayerState {
	if x != nil {
		return x.ActivePlayers
	}
	return nil
}

type StreamMediaStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMediaStateRequest) Reset() {
	*x = StreamMediaStateRequest{}
	mi := &file_pcd_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMediaStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMediaStateRequest) ProtoMessage() {}

func (x *StreamMediaStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMediaStateRequest.ProtoReflect.Descriptor instead.
func (*StreamMediaStateRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_media_proto_rawDescGZIP(), []int{3}
}

type StreamMediaStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       *MediaStatePayload     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMediaStateResponse) Reset() {
	*x = StreamMediaStateResponse{}
	mi := &file_pcd_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMediaStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMediaStateResponse) ProtoMessage() {}

func (x *StreamMediaStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMediaStateResponse.ProtoReflect.Descriptor instead.
func (*StreamMediaStateResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *StreamMediaStateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamMediaStateResponse) GetPayload() *MediaStatePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendMediaCommandRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PlayerName string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Command    string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // e.g. "play", "pause", "play_pause", "stop", "next", "previous", "seek", "set_position", "set_volume"
	// Optional arguments using 'optional' to handle nullability cleanly in Go/Kotlin
	OffsetMicroseconds   *int64   `protobuf:"varint,3,opt,name=offset_microseconds,json=offsetMicroseconds,proto3,oneof" json:"offset_microseconds,omitempty"`
	PositionMicroseconds *int64   `protobuf:"varint,4,opt,name=position_microseconds,json=positionMicroseconds,proto3,oneof" json:"position_microseconds,omitempty"`
	TrackId              *string  `protobuf:"bytes,5,opt,name=track_id,json=trackId,proto3,oneof" json:"track_id,omitempty"`
	Volume               *float64 `protobuf:"fixed64,6,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SendMediaCommandRequest) Reset() {
	*x = SendMediaCommandRequest{}
	mi := &file_pcd_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaCommandRequest) ProtoMessage() {}

func (x *SendMediaCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaCommandRequest.ProtoReflect.Descriptor instead.
func (*SendMediaCommandRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *SendMediaCommandRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *SendMediaCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SendMediaCommandRequest) GetOffsetMicroseconds() int64 {
	if x != nil && x.OffsetMicroseconds != nil {
		return *x.OffsetMicroseconds
	}
	return 0
}

func (x *SendMediaCommandRequest) GetPositionMicroseconds() int64 {
	if x != nil && x.PositionMicroseconds != nil {
		return *x.PositionMicroseconds
	}
	return 0
}

func (x *SendMediaCommandRequest) GetTrackId() string {
	if x != nil && x.TrackId != nil {
		return *x.TrackId
	}
	return ""
}

func (x *SendMediaCommandRequest) GetVolume() float64 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

type SendMediaCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMediaCommandResponse) Reset() {
	*x = SendMediaCommandResponse{}
	mi := &file_pcd_v1_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaCommandResponse) ProtoMessage() {}

func (x *SendMediaCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaCommandResponse.ProtoReflect.Descriptor instead.
func (*SendMediaCommandResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *SendMediaCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pcd_v1_media_proto protoreflect.FileDescriptor

const file_pcd_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x12pcd/v1/media.proto\x12\x06pcd.v1\"\xd6\x01\n" +
	"\x12MediaTrackMetadata\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x03(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x17\n" +
	"\aart_url\x18\x05 \x01(\tR\x06artUrl\x12\x17\n" +
	"\aart_raw\x18\x06 \x01(\fR\x06artRaw\x12/\n" +
	"\x13length_microseconds\x18\a \x01(\x03R\x12lengthMicroseconds\"\xa2\x02\n" +
	"\x10MediaPlayerState\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12#\n" +
	"\rdesktop_entry\x18\x03 \x01(\tR\fdesktopEntry\x12'\n" +
	"\x0fplayback_status\x18\x04 \x01(\tR\x0eplaybackStatus\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x123\n" +
	"\x15position_microseconds\x18\x06 \x01(\x03R\x14positionMicroseconds\x126\n" +
	"\bmetadata\x18\a \x01(\v2\x1a.pcd.v1.MediaTrackMetadataR\bmetadata\"T\n" +
	"\x11MediaStatePayload\x12?\n" +
	"\x0eactive_players\x18\x01 \x03(\v2\x18.pcd.v1.MediaPlayerStateR\ractivePlayers\"\x19\n" +
	"\x17StreamMediaStateRequest\"m\n" +
	"\x18StreamMediaStateResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x123\n" +
	"\apayload\x18\x02 \x01(\v2\x19.pcd.v1.MediaStatePayloadR\apayload\"\xcb\x02\n" +
	"\x17SendMediaCommandRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x124\n" +
	"\x13offset_microseconds\x18\x03 \x01(\x03H\x00R\x12offsetMicroseconds\x88\x01\x01\x128\n" +
	"\x15position_microseconds\x18\x04 \x01(\x03H\x01R\x14positionMicroseconds\x88\x01\x01\x12\x1e\n" +
	"\btrack_id\x18\x05 \x01(\tH\x02R\atrackId\x88\x01\x01\x12\x1b\n" +
	"\x06volume\x18\x06 \x01(\x01H\x03R\x06volume\x88\x01\x01B\x16\n" +
	"\x14_offset_microsecondsB\x18\n" +
	"\x16_position_microsecondsB\v\n" +
	"\t_track_idB\t\n" +
	"\a_volume\"4\n" +
	"\x18SendMediaCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbe\x01\n" +
	"\fMediaService\x12W\n" +
	"\x10StreamMediaState\x12\x1f.pcd.v1.StreamMediaStateRequest\x1a .pcd.v1.StreamMediaStateResponse0\x01\x12U\n" +
	"\x10SendMediaCommand\x12\x1f.pcd.v1.SendMediaCommandRequest\x1a .pcd.v1.SendMediaCommandResponseB<Z:github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1;pcdv1b\x06proto3"

var (
	file_pcd_v1_media_proto_rawDescOnce sync.Once
	file_pcd_v1_media_proto_rawDescData []byte
)

func file_pcd_v1_media_proto_rawDescGZIP() []byte {
	file_pcd_v1_media_proto_rawDescOnce.Do(func() {
		file_pcd_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcd_v1_media_proto_rawDesc), len(file_pcd_v1_media_proto_rawDesc)))
	})
	return file_pcd_v1_media_proto_rawDescData
}

var file_pcd_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pcd_v1_media_proto_goTypes = []any{
	(*MediaTrackMetadata)(nil),       // 0: pcd.v1.MediaTrackMetadata
	(*MediaPlayerState)(nil),         // 1: pcd.v1.MediaPlayerState
	(*MediaStatePayload)(nil),        // 2: pcd.v1.MediaStatePayload
	(*StreamMediaStateRequest)(nil),  // 3: pcd.v1.StreamMediaStateRequest
	(*StreamMediaStateResponse)(nil), // 4: pcd.v1.StreamMediaStateResponse
	(*SendMediaCommandRequest)(nil),  // 5: pcd.v1.SendMediaCommandRequest
	(*SendMediaCommandResponse)(nil), // 6: pcd.v1.SendMediaCommandResponse
}
var file_pcd_v1_media_proto_depIdxs = []int32{
	0, // 0: pcd.v1.MediaPlayerState.metadata:type_name -> pcd.v1.MediaTrackMetadata
	1, // 1: pcd.v1.MediaStatePayload.active_players:type_name -> pcd.v1.MediaPlayerState
	2, // 2: pcd.v1.StreamMediaStateResponse.payload:type_name -> pcd.v1.MediaStatePayload
	3, // 3: pcd.v1.MediaService.StreamMediaState:input_type -> pcd.v1.StreamMediaStateRequest
	5, // 4: pcd.v1.MediaService.SendMediaCommand:input_type -> pcd.v1.SendMediaCommandRequest
	4, // 5: pcd.v1.MediaService.StreamMediaState:output_type -> pcd.v1.StreamMediaStateResponse
	6, // 6: pcd.v1.MediaService.SendMediaCommand:output_type -> pcd.v1.SendMediaCommandResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pcd_v1_media_proto_init() }
func file_pcd_v1_media_proto_init() {
	if File_pcd_v1_media_proto != nil {
		return
	}
	file_pcd_v1_media_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcd_v1_media_proto_rawDesc), len(file_pcd_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcd_v1_media_proto_goTypes,
		DependencyIndexes: file_pcd_v1_media_proto_depIdxs,
		MessageInfos:      file_pcd_v1_media_proto_msgTypes,
	}.Build()
	File_pcd_v1_media_proto = out.File
	file_pcd_v1_media_proto_goTypes = nil
	file_pcd_v1_media_proto_depIdxs = nil
}
