// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pcd/v1/notification.proto

package pcdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ReplacesId    uint32                 `protobuf:"varint,3,opt,name=replaces_id,json=replacesId,proto3" json:"replaces_id,omitempty"`
	AppIcon       string                 `protobuf:"bytes,4,opt,name=app_icon,json=appIcon,proto3" json:"app_icon,omitempty"`
	AppIconRaw    []byte                 `protobuf:"bytes,5,opt,name=app_icon_raw,json=appIconRaw,proto3" json:"app_icon_raw,omitempty"` // Direct binary transfer, no Base64!
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Actions       []string               `protobuf:"bytes,8,rep,name=actions,proto3" json:"actions,omitempty"`
	Hints         *structpb.Struct       `protobuf:"bytes,9,opt,name=hints,proto3" json:"hints,omitempty"`
	ExpireTimeout int32                  `protobuf:"varint,10,opt,name=expire_timeout,json=expireTimeout,proto3" json:"expire_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_pcd_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationEvent) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *NotificationEvent) GetReplacesId() uint32 {
	if x != nil {
		return x.ReplacesId
	}
	return 0
}

func (x *NotificationEvent) GetAppIcon() string {
	if x != nil {
		return x.AppIcon
	}
	return ""
}

func (x *NotificationEvent) GetAppIconRaw() []byte {
	if x != nil {
		return x.AppIconRaw
	}
	return nil
}

func (x *NotificationEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *NotificationEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationEvent) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *NotificationEvent) GetHints() *structpb.Struct {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *NotificationEvent) GetExpireTimeout() int32 {
	if x != nil {
		return x.ExpireTimeout
	}
	return 0
}

type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ReplacesId    uint32                 `protobuf:"varint,2,opt,name=replaces_id,json=replacesId,proto3" json:"replaces_id,omitempty"`
	AppIcon       string                 `protobuf:"bytes,3,opt,name=app_icon,json=appIcon,proto3" json:"app_icon,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Actions       []string               `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Hints         *structpb.Struct       `protobuf:"bytes,7,opt,name=hints,proto3" json:"hints,omitempty"`
	ExpireTimeout int32                  `protobuf:"varint,8,opt,name=expire_timeout,json=expireTimeout,proto3" json:"expire_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_pcd_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *NotificationRequest) GetReplacesId() uint32 {
	if x != nil {
		return x.ReplacesId
	}
	return 0
}

func (x *NotificationRequest) GetAppIcon() string {
	if x != nil {
		return x.AppIcon
	}
	return ""
}

func (x *NotificationRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *NotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationRequest) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *NotificationRequest) GetHints() *structpb.Struct {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *NotificationRequest) GetExpireTimeout() int32 {
	if x != nil {
		return x.ExpireTimeout
	}
	return 0
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *NotificationRequest   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_pcd_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationRequest) GetNotification() *NotificationRequest {
	if x != nil {
		return x.Notification
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_pcd_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendNotificationResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TriggerNotificationActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId uint32                 `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	ActionKey      string                 `protobuf:"bytes,2,opt,name=action_key,json=actionKey,proto3" json:"action_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerNotificationActionRequest) Reset() {
	*x = TriggerNotificationActionRequest{}
	mi := &file_pcd_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerNotificationActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerNotificationActionRequest) ProtoMessage() {}

func (x *TriggerNotificationActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerNotificationActionRequest.ProtoReflect.Descriptor instead.
func (*TriggerNotificationActionRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerNotificationActionRequest) GetNotificationId() uint32 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *TriggerNotificationActionRequest) GetActionKey() string {
	if x != nil {
		return x.ActionKey
	}
	return ""
}

type TriggerNotificationActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerNotificationActionResponse) Reset() {
	*x = TriggerNotificationActionResponse{}
	mi := &file_pcd_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerNotificationActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerNotificationActionResponse) ProtoMessage() {}

func (x *TriggerNotificationActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerNotificationActionResponse.ProtoReflect.Descriptor instead.
func (*TriggerNotificationActionResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerNotificationActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DismissNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId uint32                 `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DismissNotificationRequest) Reset() {
	*x = DismissNotificationRequest{}
	mi := &file_pcd_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissNotificationRequest) ProtoMessage() {}

func (x *DismissNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissNotificationRequest.ProtoReflect.Descriptor instead.
func (*DismissNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *DismissNotificationRequest) GetNotificationId() uint32 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type DismissNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissNotificationResponse) Reset() {
	*x = DismissNotificationResponse{}
	mi := &file_pcd_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissNotificationResponse) ProtoMessage() {}

func (x *DismissNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissNotificationResponse.ProtoReflect.Descriptor instead.
func (*DismissNotificationResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *DismissNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StreamNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNotificationsRequest) Reset() {
	*x = StreamNotificationsRequest{}
	mi := &file_pcd_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsRequest) ProtoMessage() {}

func (x *StreamNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNotificationsRequest.ProtoReflect.Descriptor instead.
func (*StreamNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{8}
}

type StreamNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Event         *NotificationEvent     `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNotificationsResponse) Reset() {
	*x = StreamNotificationsResponse{}
	mi := &file_pcd_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsResponse) ProtoMessage() {}

func (x *StreamNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNotificationsResponse.ProtoReflect.Descriptor instead.
func (*StreamNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *StreamNotificationsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamNotificationsResponse) GetEvent() *NotificationEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_pcd_v1_notification_proto protoreflect.FileDescriptor

const file_pcd_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\x19pcd/v1/notification.proto\x12\x06pcd.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xba\x02\n" +
	"\x11NotificationEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1f\n" +
	"\vreplaces_id\x18\x03 \x01(\rR\n" +
	"replacesId\x12\x19\n" +
	"\bapp_icon\x18\x04 \x01(\tR\aappIcon\x12 \n" +
	"\fapp_icon_raw\x18\x05 \x01(\fR\n" +
	"appIconRaw\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x12\x18\n" +
	"\aactions\x18\b \x03(\tR\aactions\x12-\n" +
	"\x05hints\x18\t \x01(\v2\x17.google.protobuf.StructR\x05hints\x12%\n" +
	"\x0eexpire_timeout\x18\n" +
	" \x01(\x05R\rexpireTimeout\"\x8a\x02\n" +
	"\x13NotificationRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1f\n" +
	"\vreplaces_id\x18\x02 \x01(\rR\n" +
	"replacesId\x12\x19\n" +
	"\bapp_icon\x18\x03 \x01(\tR\aappIcon\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x18\n" +
	"\aactions\x18\x06 \x03(\tR\aactions\x12-\n" +
	"\x05hints\x18\a \x01(\v2\x17.google.protobuf.StructR\x05hints\x12%\n" +
	"\x0eexpire_timeout\x18\b \x01(\x05R\rexpireTimeout\"Z\n" +
	"\x17SendNotificationRequest\x12?\n" +
	"\fnotification\x18\x01 \x01(\v2\x1b.pcd.v1.NotificationRequestR\fnotification\"*\n" +
	"\x18SendNotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"j\n" +
	" TriggerNotificationActionRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\rR\x0enotificationId\x12\x1d\n" +
	"\n" +
	"action_key\x18\x02 \x01(\tR\tactionKey\"=\n" +
	"!TriggerNotificationActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x1aDismissNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\rR\x0enotificationId\"7\n" +
	"\x1bDismissNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1c\n" +
	"\x1aStreamNotificationsRequest\"l\n" +
	"\x1bStreamNotificationsResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12/\n" +
	"\x05event\x18\x02 \x01(\v2\x19.pcd.v1.NotificationEventR\x05event2\xa0\x03\n" +
	"\x13NotificationService\x12`\n" +
	"\x13StreamNotifications\x12\".pcd.v1.StreamNotificationsRequest\x1a#.pcd.v1.StreamNotificationsResponse0\x01\x12U\n" +
	"\x10SendNotification\x12\x1f.pcd.v1.SendNotificationRequest\x1a .pcd.v1.SendNotificationResponse\x12p\n" +
	"\x19TriggerNotificationAction\x12(.pcd.v1.TriggerNotificationActionRequest\x1a).pcd.v1.TriggerNotificationActionResponse\x12^\n" +
	"\x13DismissNotification\x12\".pcd.v1.DismissNotificationRequest\x1a#.pcd.v1.DismissNotificationResponseB<Z:github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1;pcdv1b\x06proto3"

var (
	file_pcd_v1_notification_proto_rawDescOnce sync.Once
	file_pcd_v1_notification_proto_rawDescData []byte
)

func file_pcd_v1_notification_proto_rawDescGZIP() []byte {
	file_pcd_v1_notification_proto_rawDescOnce.Do(func() {
		file_pcd_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcd_v1_notification_proto_rawDesc), len(file_pcd_v1_notification_proto_rawDesc)))
	})
	return file_pcd_v1_notification_proto_rawDescData
}

var file_pcd_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pcd_v1_notification_proto_goTypes = []any{
	(*NotificationEvent)(nil),                 // 0: pcd.v1.NotificationEvent
	(*NotificationRequest)(nil),               // 1: pcd.v1.NotificationRequest
	(*SendNotificationRequest)(nil),           // 2: pcd.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil),          // 3: pcd.v1.SendNotificationResponse
	(*TriggerNotificationActionRequest)(nil),  // 4: pcd.v1.TriggerNotificationActionRequest
	(*TriggerNotificationActionResponse)(nil), // 5: pcd.v1.TriggerNotificationActionResponse
	(*DismissNotificationRequest)(nil),        // 6: pcd.v1.DismissNotificationRequest
	(*DismissNotificationResponse)(nil),       // 7: pcd.v1.DismissNotificationResponse
	(*StreamNotificationsRequest)(nil),        // 8: pcd.v1.StreamNotificationsRequest
	(*StreamNotificationsResponse)(nil),       // 9: pcd.v1.StreamNotificationsResponse
	(*structpb.Struct)(nil),                   // 10: google.protobuf.Struct
}
var file_pcd_v1_notification_proto_depIdxs = []int32{
	10, // 0: pcd.v1.NotificationEvent.hints:type_name -> google.protobuf.Struct
	10, // 1: pcd.v1.NotificationRequest.hints:type_name -> google.protobuf.Struct
	1,  // 2: pcd.v1.SendNotificationRequest.notification:type_name -> pcd.v1.NotificationRequest
	0,  // 3: pcd.v1.StreamNotificationsResponse.event:type_name -> pcd.v1.NotificationEvent
	8,  // 4: pcd.v1.NotificationService.StreamNotifications:input_type -> pcd.v1.StreamNotificationsRequest
	2,  // 5: pcd.v1.NotificationService.SendNotification:input_type -> pcd.v1.SendNotificationRequest
	4,  // 6: pcd.v1.NotificationService.TriggerNotificationAction:input_type -> pcd.v1.TriggerNotificationActionRequest
	6,  // 7: pcd.v1.NotificationService.DismissNotification:input_type -> pcd.v1.DismissNotificationRequest
	9,  // 8: pcd.v1.NotificationService.StreamNotifications:output_type -> pcd.v1.StreamNotificationsResponse
	3,  // 9: pcd.v1.NotificationService.SendNotification:output_type -> pcd.v1.SendNotificationResponse
	5,  // 10: pcd.v1.NotificationService.TriggerNotificationAction:output_type -> pcd.v1.TriggerNotificationActionResponse
	7,  // 11: pcd.v1.NotificationService.DismissNotification:output_type -> pcd.v1.DismissNotificationResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pcd_v1_notification_proto_init() }
func file_pcd_v1_notification_proto_init() {
	if File_pcd_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcd_v1_notification_proto_rawDesc), len(file_pcd_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcd_v1_notification_proto_goTypes,
		DependencyIndexes: file_pcd_v1_notification_proto_depIdxs,
		MessageInfos:      file_pcd_v1_notification_proto_msgTypes,
	}.Build()
	File_pcd_v1_notification_proto = out.File
	file_pcd_v1_notification_proto_goTypes = nil
	file_pcd_v1_notification_proto_depIdxs = nil
}
