// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pcd/v1/system.proto

package pcdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionLockEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locked        bool                   `protobuf:"varint,1,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionLockEvent) Reset() {
	*x = SessionLockEvent{}
	mi := &file_pcd_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionLockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionLockEvent) ProtoMessage() {}

func (x *SessionLockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionLockEvent.ProtoReflect.Descriptor instead.
func (*SessionLockEvent) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *SessionLockEvent) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

type DpmsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "on", "off"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DpmsEvent) Reset() {
	*x = DpmsEvent{}
	mi := &file_pcd_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpmsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpmsEvent) ProtoMessage() {}

func (x *DpmsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpmsEvent.ProtoReflect.Descriptor instead.
func (*DpmsEvent) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *DpmsEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type PowerProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerProfile) Reset() {
	*x = PowerProfile{}
	mi := &file_pcd_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerProfile) ProtoMessage() {}

func (x *PowerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerProfile.ProtoReflect.Descriptor instead.
func (*PowerProfile) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *PowerProfile) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type PowerProfileState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveProfile     string                 `protobuf:"bytes,1,opt,name=active_profile,json=activeProfile,proto3" json:"active_profile,omitempty"`
	AvailableProfiles []*PowerProfile        `protobuf:"bytes,2,rep,name=available_profiles,json=availableProfiles,proto3" json:"available_profiles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PowerProfileState) Reset() {
	*x = PowerProfileState{}
	mi := &file_pcd_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerProfileState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerProfileState) ProtoMessage() {}

func (x *PowerProfileState) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerProfileState.ProtoReflect.Descriptor instead.
func (*PowerProfileState) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *PowerProfileState) GetActiveProfile() string {
	if x != nil {
		return x.ActiveProfile
	}
	return ""
}

func (x *PowerProfileState) GetAvailableProfiles() []*PowerProfile {
	if x != nil {
		return x.AvailableProfiles
	}
	return nil
}

type StreamSystemStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSystemStateRequest) Reset() {
	*x = StreamSystemStateRequest{}
	mi := &file_pcd_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSystemStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSystemStateRequest) ProtoMessage() {}

func (x *StreamSystemStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSystemStateRequest.ProtoReflect.Descriptor instead.
func (*StreamSystemStateRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{4}
}

type StreamSystemStateResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamSystemStateResponse_SessionLock
	//	*StreamSystemStateResponse_DpmsState
	//	*StreamSystemStateResponse_PowerProfileState
	Event         isStreamSystemStateResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSystemStateResponse) Reset() {
	*x = StreamSystemStateResponse{}
	mi := &file_pcd_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSystemStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSystemStateResponse) ProtoMessage() {}

func (x *StreamSystemStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSystemStateResponse.ProtoReflect.Descriptor instead.
func (*StreamSystemStateResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *StreamSystemStateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamSystemStateResponse) GetEvent() isStreamSystemStateResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamSystemStateResponse) GetSessionLock() *SessionLockEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamSystemStateResponse_SessionLock); ok {
			return x.SessionLock
		}
	}
	return nil
}

func (x *StreamSystemStateResponse) GetDpmsState() *DpmsEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamSystemStateResponse_DpmsState); ok {
			return x.DpmsState
		}
	}
	return nil
}

func (x *StreamSystemStateResponse) GetPowerProfileState() *PowerProfileState {
	if x != nil {
		if x, ok := x.Event.(*StreamSystemStateResponse_PowerProfileState); ok {
			return x.PowerProfileState
		}
	}
	return nil
}

type isStreamSystemStateResponse_Event interface {
	isStreamSystemStateResponse_Event()
}

type StreamSystemStateResponse_SessionLock struct {
	SessionLock *SessionLockEvent `protobuf:"bytes,2,opt,name=session_lock,json=sessionLock,proto3,oneof"`
}

type StreamSystemStateResponse_DpmsState struct {
	DpmsState *DpmsEvent `protobuf:"bytes,3,opt,name=dpms_state,json=dpmsState,proto3,oneof"`
}

type StreamSystemStateResponse_PowerProfileState struct {
	PowerProfileState *PowerProfileState `protobuf:"bytes,4,opt,name=power_profile_state,json=powerProfileState,proto3,oneof"`
}

func (*StreamSystemStateResponse_SessionLock) isStreamSystemStateResponse_Event() {}

func (*StreamSystemStateResponse_DpmsState) isStreamSystemStateResponse_Event() {}

func (*StreamSystemStateResponse_PowerProfileState) isStreamSystemStateResponse_Event() {}

type ExecuteSystemActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // e.g. "suspend", "disconnect"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSystemActionRequest) Reset() {
	*x = ExecuteSystemActionRequest{}
	mi := &file_pcd_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSystemActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSystemActionRequest) ProtoMessage() {}

func (x *ExecuteSystemActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSystemActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSystemActionRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteSystemActionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ExecuteSystemActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSystemActionResponse) Reset() {
	*x = ExecuteSystemActionResponse{}
	mi := &file_pcd_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSystemActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSystemActionResponse) ProtoMessage() {}

func (x *ExecuteSystemActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSystemActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSystemActionResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteSystemActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetPowerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPowerProfileRequest) Reset() {
	*x = SetPowerProfileRequest{}
	mi := &file_pcd_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPowerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPowerProfileRequest) ProtoMessage() {}

func (x *SetPowerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPowerProfileRequest.ProtoReflect.Descriptor instead.
func (*SetPowerProfileRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *SetPowerProfileRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type SetPowerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPowerProfileResponse) Reset() {
	*x = SetPowerProfileResponse{}
	mi := &file_pcd_v1_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPowerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPowerProfileResponse) ProtoMessage() {}

func (x *SetPowerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPowerProfileResponse.ProtoReflect.Descriptor instead.
func (*SetPowerProfileResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_system_proto_rawDescGZIP(), []int{9}
}

func (x *SetPowerProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pcd_v1_system_proto protoreflect.FileDescriptor

const file_pcd_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x13pcd/v1/system.proto\x12\x06pcd.v1\"*\n" +
	"\x10SessionLockEvent\x12\x16\n" +
	"\x06locked\x18\x01 \x01(\bR\x06locked\"!\n" +
	"\tDpmsEvent\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"(\n" +
	"\fPowerProfile\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"\x7f\n" +
	"\x11PowerProfileState\x12%\n" +
	"\x0eactive_profile\x18\x01 \x01(\tR\ractiveProfile\x12C\n" +
	"\x12available_profiles\x18\x02 \x03(\v2\x14.pcd.v1.PowerProfileR\x11availableProfiles\"\x1a\n" +
	"\x18StreamSystemStateRequest\"\x82\x02\n" +
	"\x19StreamSystemStateResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12=\n" +
	"\fsession_lock\x18\x02 \x01(\v2\x18.pcd.v1.SessionLockEventH\x00R\vsessionLock\x122\n" +
	"\n" +
	"dpms_state\x18\x03 \x01(\v2\x11.pcd.v1.DpmsEventH\x00R\tdpmsState\x12K\n" +
	"\x13power_profile_state\x18\x04 \x01(\v2\x19.pcd.v1.PowerProfileStateH\x00R\x11powerProfileStateB\a\n" +
	"\x05event\"6\n" +
	"\x1aExecuteSystemActionRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"7\n" +
	"\x1bExecuteSystemActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x16SetPowerProfileRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"3\n" +
	"\x17SetPowerProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9f\x02\n" +
	"\rSystemService\x12Z\n" +
	"\x11StreamSystemState\x12 .pcd.v1.StreamSystemStateRequest\x1a!.pcd.v1.StreamSystemStateResponse0\x01\x12^\n" +
	"\x13ExecuteSystemAction\x12\".pcd.v1.ExecuteSystemActionRequest\x1a#.pcd.v1.ExecuteSystemActionResponse\x12R\n" +
	"\x0fSetPowerProfile\x12\x1e.pcd.v1.SetPowerProfileRequest\x1a\x1f.pcd.v1.SetPowerProfileResponseB<Z:github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1;pcdv1b\x06proto3"

var (
	file_pcd_v1_system_proto_rawDescOnce sync.Once
	file_pcd_v1_system_proto_rawDescData []byte
)

func file_pcd_v1_system_proto_rawDescGZIP() []byte {
	file_pcd_v1_system_proto_rawDescOnce.Do(func() {
		file_pcd_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcd_v1_system_proto_rawDesc), len(file_pcd_v1_system_proto_rawDesc)))
	})
	return file_pcd_v1_system_proto_rawDescData
}

var file_pcd_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pcd_v1_system_proto_goTypes = []any{
	(*SessionLockEvent)(nil),            // 0: pcd.v1.SessionLockEvent
	(*DpmsEvent)(nil),                   // 1: pcd.v1.DpmsEvent
	(*PowerProfile)(nil),                // 2: pcd.v1.PowerProfile
	(*PowerProfileState)(nil),           // 3: pcd.v1.PowerProfileState
	(*StreamSystemStateRequest)(nil),    // 4: pcd.v1.StreamSystemStateRequest
	(*StreamSystemStateResponse)(nil),   // 5: pcd.v1.StreamSystemStateResponse
	(*ExecuteSystemActionRequest)(nil),  // 6: pcd.v1.ExecuteSystemActionRequest
	(*ExecuteSystemActionResponse)(nil), // 7: pcd.v1.ExecuteSystemActionResponse
	(*SetPowerProfileRequest)(nil),      // 8: pcd.v1.SetPowerProfileRequest
	(*SetPowerProfileResponse)(nil),     // 9: pcd.v1.SetPowerProfileResponse
}
var file_pcd_v1_system_proto_depIdxs = []int32{
	2, // 0: pcd.v1.PowerProfileState.available_profiles:type_name -> pcd.v1.PowerProfile
	0, // 1: pcd.v1.StreamSystemStateResponse.session_lock:type_name -> pcd.v1.SessionLockEvent
	1, // 2: pcd.v1.StreamSystemStateResponse.dpms_state:type_name -> pcd.v1.DpmsEvent
	3, // 3: pcd.v1.StreamSystemStateResponse.power_profile_state:type_name -> pcd.v1.PowerProfileState
	4, // 4: pcd.v1.SystemService.StreamSystemState:input_type -> pcd.v1.StreamSystemStateRequest
	6, // 5: pcd.v1.SystemService.ExecuteSystemAction:input_type -> pcd.v1.ExecuteSystemActionRequest
	8, // 6: pcd.v1.SystemService.SetPowerProfile:input_type -> pcd.v1.SetPowerProfileRequest
	5, // 7: pcd.v1.SystemService.StreamSystemState:output_type -> pcd.v1.StreamSystemStateResponse
	7, // 8: pcd.v1.SystemService.ExecuteSystemAction:output_type -> pcd.v1.ExecuteSystemActionResponse
	9, // 9: pcd.v1.SystemService.SetPowerProfile:output_type -> pcd.v1.SetPowerProfileResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pcd_v1_system_proto_init() }
func file_pcd_v1_system_proto_init() {
	if File_pcd_v1_system_proto != nil {
		return
	}
	file_pcd_v1_system_proto_msgTypes[5].OneofWrappers = []any{
		(*StreamSystemStateResponse_SessionLock)(nil),
		(*StreamSystemStateResponse_DpmsState)(nil),
		(*StreamSystemStateResponse_PowerProfileState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcd_v1_system_proto_rawDesc), len(file_pcd_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcd_v1_system_proto_goTypes,
		DependencyIndexes: file_pcd_v1_system_proto_depIdxs,
		MessageInfos:      file_pcd_v1_system_proto_msgTypes,
	}.Build()
	File_pcd_v1_system_proto = out.File
	file_pcd_v1_system_proto_goTypes = nil
	file_pcd_v1_system_proto_depIdxs = nil
}
