// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pcd/v1/telemetry.proto

package pcdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPUUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent      float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	TempCelsius       float64                `protobuf:"fixed64,2,opt,name=temp_celsius,json=tempCelsius,proto3" json:"temp_celsius,omitempty"`
	PowerWatts        float64                `protobuf:"fixed64,3,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	TmaxCelsius       float64                `protobuf:"fixed64,4,opt,name=tmax_celsius,json=tmaxCelsius,proto3" json:"tmax_celsius,omitempty"`
	CoresUsagePercent []float64              `protobuf:"fixed64,5,rep,packed,name=cores_usage_percent,json=coresUsagePercent,proto3" json:"cores_usage_percent,omitempty"`
	FreqMhz           float64                `protobuf:"fixed64,6,opt,name=freq_mhz,json=freqMhz,proto3" json:"freq_mhz,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CPUUsage) Reset() {
	*x = CPUUsage{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUUsage) ProtoMessage() {}

func (x *CPUUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUUsage.ProtoReflect.Descriptor instead.
func (*CPUUsage) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *CPUUsage) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CPUUsage) GetTempCelsius() float64 {
	if x != nil {
		return x.TempCelsius
	}
	return 0
}

func (x *CPUUsage) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *CPUUsage) GetTmaxCelsius() float64 {
	if x != nil {
		return x.TmaxCelsius
	}
	return 0
}

func (x *CPUUsage) GetCoresUsagePercent() []float64 {
	if x != nil {
		return x.CoresUsagePercent
	}
	return nil
}

func (x *CPUUsage) GetFreqMhz() float64 {
	if x != nil {
		return x.FreqMhz
	}
	return 0
}

type GPUUsage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent    float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	TempCelsius     float64                `protobuf:"fixed64,2,opt,name=temp_celsius,json=tempCelsius,proto3" json:"temp_celsius,omitempty"`
	VramUsedBytes   uint64                 `protobuf:"varint,3,opt,name=vram_used_bytes,json=vramUsedBytes,proto3" json:"vram_used_bytes,omitempty"`
	VramTotalBytes  uint64                 `protobuf:"varint,4,opt,name=vram_total_bytes,json=vramTotalBytes,proto3" json:"vram_total_bytes,omitempty"`
	PowerWatts      float64                `protobuf:"fixed64,5,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	VramTempCelsius float64                `protobuf:"fixed64,6,opt,name=vram_temp_celsius,json=vramTempCelsius,proto3" json:"vram_temp_celsius,omitempty"`
	VramFreqMhz     float64                `protobuf:"fixed64,7,opt,name=vram_freq_mhz,json=vramFreqMhz,proto3" json:"vram_freq_mhz,omitempty"`
	TmaxCelsius     float64                `protobuf:"fixed64,8,opt,name=tmax_celsius,json=tmaxCelsius,proto3" json:"tmax_celsius,omitempty"`
	FreqMhz         float64                `protobuf:"fixed64,9,opt,name=freq_mhz,json=freqMhz,proto3" json:"freq_mhz,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GPUUsage) Reset() {
	*x = GPUUsage{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUUsage) ProtoMessage() {}

func (x *GPUUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUUsage.ProtoReflect.Descriptor instead.
func (*GPUUsage) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *GPUUsage) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *GPUUsage) GetTempCelsius() float64 {
	if x != nil {
		return x.TempCelsius
	}
	return 0
}

func (x *GPUUsage) GetVramUsedBytes() uint64 {
	if x != nil {
		return x.VramUsedBytes
	}
	return 0
}

func (x *GPUUsage) GetVramTotalBytes() uint64 {
	if x != nil {
		return x.VramTotalBytes
	}
	return 0
}

func (x *GPUUsage) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *GPUUsage) GetVramTempCelsius() float64 {
	if x != nil {
		return x.VramTempCelsius
	}
	return 0
}

func (x *GPUUsage) GetVramFreqMhz() float64 {
	if x != nil {
		return x.VramFreqMhz
	}
	return 0
}

func (x *GPUUsage) GetTmaxCelsius() float64 {
	if x != nil {
		return x.TmaxCelsius
	}
	return 0
}

func (x *GPUUsage) GetFreqMhz() float64 {
	if x != nil {
		return x.FreqMhz
	}
	return 0
}

type RAMUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     uint64                 `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAMUsage) Reset() {
	*x = RAMUsage{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAMUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAMUsage) ProtoMessage() {}

func (x *RAMUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAMUsage.ProtoReflect.Descriptor instead.
func (*RAMUsage) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *RAMUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *RAMUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *RAMUsage) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type SwapUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     uint64                 `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapUsage) Reset() {
	*x = SwapUsage{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapUsage) ProtoMessage() {}

func (x *SwapUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapUsage.ProtoReflect.Descriptor instead.
func (*SwapUsage) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *SwapUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *SwapUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *SwapUsage) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type ZRAMUsage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrigDataSizeBytes  uint64                 `protobuf:"varint,1,opt,name=orig_data_size_bytes,json=origDataSizeBytes,proto3" json:"orig_data_size_bytes,omitempty"`
	ComprDataSizeBytes uint64                 `protobuf:"varint,2,opt,name=compr_data_size_bytes,json=comprDataSizeBytes,proto3" json:"compr_data_size_bytes,omitempty"`
	MemUsedTotalBytes  uint64                 `protobuf:"varint,3,opt,name=mem_used_total_bytes,json=memUsedTotalBytes,proto3" json:"mem_used_total_bytes,omitempty"`
	TotalBytes         uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	CompressionRatio   float64                `protobuf:"fixed64,5,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ZRAMUsage) Reset() {
	*x = ZRAMUsage{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZRAMUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRAMUsage) ProtoMessage() {}

func (x *ZRAMUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRAMUsage.ProtoReflect.Descriptor instead.
func (*ZRAMUsage) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *ZRAMUsage) GetOrigDataSizeBytes() uint64 {
	if x != nil {
		return x.OrigDataSizeBytes
	}
	return 0
}

func (x *ZRAMUsage) GetComprDataSizeBytes() uint64 {
	if x != nil {
		return x.ComprDataSizeBytes
	}
	return 0
}

func (x *ZRAMUsage) GetMemUsedTotalBytes() uint64 {
	if x != nil {
		return x.MemUsedTotalBytes
	}
	return 0
}

func (x *ZRAMUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ZRAMUsage) GetCompressionRatio() float64 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

type TelemetryFlags struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CpuUsageSupported       bool                   `protobuf:"varint,1,opt,name=cpu_usage_supported,json=cpuUsageSupported,proto3" json:"cpu_usage_supported,omitempty"`
	CpuCoresUsageSupported  bool                   `protobuf:"varint,2,opt,name=cpu_cores_usage_supported,json=cpuCoresUsageSupported,proto3" json:"cpu_cores_usage_supported,omitempty"`
	CpuTempSupported        bool                   `protobuf:"varint,3,opt,name=cpu_temp_supported,json=cpuTempSupported,proto3" json:"cpu_temp_supported,omitempty"`
	CpuFreqSupported        bool                   `protobuf:"varint,4,opt,name=cpu_freq_supported,json=cpuFreqSupported,proto3" json:"cpu_freq_supported,omitempty"`
	CpuPowerSupported       bool                   `protobuf:"varint,5,opt,name=cpu_power_supported,json=cpuPowerSupported,proto3" json:"cpu_power_supported,omitempty"`
	CpuTempTmaxSupported    bool                   `protobuf:"varint,6,opt,name=cpu_temp_tmax_supported,json=cpuTempTmaxSupported,proto3" json:"cpu_temp_tmax_supported,omitempty"`
	RamSupported            bool                   `protobuf:"varint,7,opt,name=ram_supported,json=ramSupported,proto3" json:"ram_supported,omitempty"`
	SwapSupported           bool                   `protobuf:"varint,8,opt,name=swap_supported,json=swapSupported,proto3" json:"swap_supported,omitempty"`
	ZramSupported           bool                   `protobuf:"varint,9,opt,name=zram_supported,json=zramSupported,proto3" json:"zram_supported,omitempty"`
	GpuSupported            bool                   `protobuf:"varint,10,opt,name=gpu_supported,json=gpuSupported,proto3" json:"gpu_supported,omitempty"`
	GpuUsageSupported       bool                   `protobuf:"varint,11,opt,name=gpu_usage_supported,json=gpuUsageSupported,proto3" json:"gpu_usage_supported,omitempty"`
	GpuTempSupported        bool                   `protobuf:"varint,12,opt,name=gpu_temp_supported,json=gpuTempSupported,proto3" json:"gpu_temp_supported,omitempty"`
	GpuVramSupported        bool                   `protobuf:"varint,13,opt,name=gpu_vram_supported,json=gpuVramSupported,proto3" json:"gpu_vram_supported,omitempty"`
	GpuFreqSupported        bool                   `protobuf:"varint,14,opt,name=gpu_freq_supported,json=gpuFreqSupported,proto3" json:"gpu_freq_supported,omitempty"`
	GpuPowerSupported       bool                   `protobuf:"varint,15,opt,name=gpu_power_supported,json=gpuPowerSupported,proto3" json:"gpu_power_supported,omitempty"`
	GpuVramTempSupported    bool                   `protobuf:"varint,16,opt,name=gpu_vram_temp_supported,json=gpuVramTempSupported,proto3" json:"gpu_vram_temp_supported,omitempty"`
	GpuVramFreqSupported    bool                   `protobuf:"varint,17,opt,name=gpu_vram_freq_supported,json=gpuVramFreqSupported,proto3" json:"gpu_vram_freq_supported,omitempty"`
	GpuTempTmaxSupported    bool                   `protobuf:"varint,18,opt,name=gpu_temp_tmax_supported,json=gpuTempTmaxSupported,proto3" json:"gpu_temp_tmax_supported,omitempty"`
	OsdSupported            bool                   `protobuf:"varint,19,opt,name=osd_supported,json=osdSupported,proto3" json:"osd_supported,omitempty"`
	PeripheralsSupported    bool                   `protobuf:"varint,20,opt,name=peripherals_supported,json=peripheralsSupported,proto3" json:"peripherals_supported,omitempty"`
	PackageUpdatesSupported bool                   `protobuf:"varint,21,opt,name=package_updates_supported,json=packageUpdatesSupported,proto3" json:"package_updates_supported,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TelemetryFlags) Reset() {
	*x = TelemetryFlags{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFlags) ProtoMessage() {}

func (x *TelemetryFlags) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFlags.ProtoReflect.Descriptor instead.
func (*TelemetryFlags) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryFlags) GetCpuUsageSupported() bool {
	if x != nil {
		return x.CpuUsageSupported
	}
	return false
}

func (x *TelemetryFlags) GetCpuCoresUsageSupported() bool {
	if x != nil {
		return x.CpuCoresUsageSupported
	}
	return false
}

func (x *TelemetryFlags) GetCpuTempSupported() bool {
	if x != nil {
		return x.CpuTempSupported
	}
	return false
}

func (x *TelemetryFlags) GetCpuFreqSupported() bool {
	if x != nil {
		return x.CpuFreqSupported
	}
	return false
}

func (x *TelemetryFlags) GetCpuPowerSupported() bool {
	if x != nil {
		return x.CpuPowerSupported
	}
	return false
}

func (x *TelemetryFlags) GetCpuTempTmaxSupported() bool {
	if x != nil {
		return x.CpuTempTmaxSupported
	}
	return false
}

func (x *TelemetryFlags) GetRamSupported() bool {
	if x != nil {
		return x.RamSupported
	}
	return false
}

func (x *TelemetryFlags) GetSwapSupported() bool {
	if x != nil {
		return x.SwapSupported
	}
	return false
}

func (x *TelemetryFlags) GetZramSupported() bool {
	if x != nil {
		return x.ZramSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuSupported() bool {
	if x != nil {
		return x.GpuSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuUsageSupported() bool {
	if x != nil {
		return x.GpuUsageSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuTempSupported() bool {
	if x != nil {
		return x.GpuTempSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuVramSupported() bool {
	if x != nil {
		return x.GpuVramSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuFreqSupported() bool {
	if x != nil {
		return x.GpuFreqSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuPowerSupported() bool {
	if x != nil {
		return x.GpuPowerSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuVramTempSupported() bool {
	if x != nil {
		return x.GpuVramTempSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuVramFreqSupported() bool {
	if x != nil {
		return x.GpuVramFreqSupported
	}
	return false
}

func (x *TelemetryFlags) GetGpuTempTmaxSupported() bool {
	if x != nil {
		return x.GpuTempTmaxSupported
	}
	return false
}

func (x *TelemetryFlags) GetOsdSupported() bool {
	if x != nil {
		return x.OsdSupported
	}
	return false
}

func (x *TelemetryFlags) GetPeripheralsSupported() bool {
	if x != nil {
		return x.PeripheralsSupported
	}
	return false
}

func (x *TelemetryFlags) GetPackageUpdatesSupported() bool {
	if x != nil {
		return x.PackageUpdatesSupported
	}
	return false
}

type TelemetryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cpu           *CPUUsage              `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu           *GPUUsage              `protobuf:"bytes,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Ram           *RAMUsage              `protobuf:"bytes,4,opt,name=ram,proto3" json:"ram,omitempty"`
	Swap          *SwapUsage             `protobuf:"bytes,5,opt,name=swap,proto3" json:"swap,omitempty"`
	Zram          *ZRAMUsage             `protobuf:"bytes,6,opt,name=zram,proto3" json:"zram,omitempty"`
	Flags         *TelemetryFlags        `protobuf:"bytes,7,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload) ProtoMessage() {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload.ProtoReflect.Descriptor instead.
func (*TelemetryPayload) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryPayload) GetCpu() *CPUUsage {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *TelemetryPayload) GetGpu() *GPUUsage {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *TelemetryPayload) GetRam() *RAMUsage {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *TelemetryPayload) GetSwap() *SwapUsage {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *TelemetryPayload) GetZram() *ZRAMUsage {
	if x != nil {
		return x.Zram
	}
	return nil
}

func (x *TelemetryPayload) GetFlags() *TelemetryFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

type StreamTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalMs    int32                  `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryRequest) Reset() {
	*x = StreamTelemetryRequest{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryRequest) ProtoMessage() {}

func (x *StreamTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *StreamTelemetryRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StreamTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *TelemetryPayload      `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryResponse) Reset() {
	*x = StreamTelemetryResponse{}
	mi := &file_pcd_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryResponse) ProtoMessage() {}

func (x *StreamTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcd_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryResponse.ProtoReflect.Descriptor instead.
func (*StreamTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_pcd_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *StreamTelemetryResponse) GetPayload() *TelemetryPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pcd_v1_telemetry_proto protoreflect.FileDescriptor

const file_pcd_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x16pcd/v1/telemetry.proto\x12\x06pcd.v1\"\xe1\x01\n" +
	"\bCPUUsage\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12!\n" +
	"\ftemp_celsius\x18\x02 \x01(\x01R\vtempCelsius\x12\x1f\n" +
	"\vpower_watts\x18\x03 \x01(\x01R\n" +
	"powerWatts\x12!\n" +
	"\ftmax_celsius\x18\x04 \x01(\x01R\vtmaxCelsius\x12.\n" +
	"\x13cores_usage_percent\x18\x05 \x03(\x01R\x11coresUsagePercent\x12\x19\n" +
	"\bfreq_mhz\x18\x06 \x01(\x01R\afreqMhz\"\xd3\x02\n" +
	"\bGPUUsage\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12!\n" +
	"\ftemp_celsius\x18\x02 \x01(\x01R\vtempCelsius\x12&\n" +
	"\x0fvram_used_bytes\x18\x03 \x01(\x04R\rvramUsedBytes\x12(\n" +
	"\x10vram_total_bytes\x18\x04 \x01(\x04R\x0evramTotalBytes\x12\x1f\n" +
	"\vpower_watts\x18\x05 \x01(\x01R\n" +
	"powerWatts\x12*\n" +
	"\x11vram_temp_celsius\x18\x06 \x01(\x01R\x0fvramTempCelsius\x12\"\n" +
	"\rvram_freq_mhz\x18\a \x01(\x01R\vvramFreqMhz\x12!\n" +
	"\ftmax_celsius\x18\b \x01(\x01R\vtmaxCelsius\x12\x19\n" +
	"\bfreq_mhz\x18\t \x01(\x01R\afreqMhz\"j\n" +
	"\bRAMUsage\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"k\n" +
	"\tSwapUsage\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"\xee\x01\n" +
	"\tZRAMUsage\x12/\n" +
	"\x14orig_data_size_bytes\x18\x01 \x01(\x04R\x11origDataSizeBytes\x121\n" +
	"\x15compr_data_size_bytes\x18\x02 \x01(\x04R\x12comprDataSizeBytes\x12/\n" +
	"\x14mem_used_total_bytes\x18\x03 \x01(\x04R\x11memUsedTotalBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12+\n" +
	"\x11compression_ratio\x18\x05 \x01(\x01R\x10compressionRatio\"\xfb\a\n" +
	"\x0eTelemetryFlags\x12.\n" +
	"\x13cpu_usage_supported\x18\x01 \x01(\bR\x11cpuUsageSupported\x129\n" +
	"\x19cpu_cores_usage_supported\x18\x02 \x01(\bR\x16cpuCoresUsageSupported\x12,\n" +
	"\x12cpu_temp_supported\x18\x03 \x01(\bR\x10cpuTempSupported\x12,\n" +
	"\x12cpu_freq_supported\x18\x04 \x01(\bR\x10cpuFreqSupported\x12.\n" +
	"\x13cpu_power_supported\x18\x05 \x01(\bR\x11cpuPowerSupported\x125\n" +
	"\x17cpu_temp_tmax_supported\x18\x06 \x01(\bR\x14cpuTempTmaxSupported\x12#\n" +
	"\rram_supported\x18\a \x01(\bR\framSupported\x12%\n" +
	"\x0eswap_supported\x18\b \x01(\bR\rswapSupported\x12%\n" +
	"\x0ezram_supported\x18\t \x01(\bR\rzramSupported\x12#\n" +
	"\rgpu_supported\x18\n" +
	" \x01(\bR\fgpuSupported\x12.\n" +
	"\x13gpu_usage_supported\x18\v \x01(\bR\x11gpuUsageSupported\x12,\n" +
	"\x12gpu_temp_supported\x18\f \x01(\bR\x10gpuTempSupported\x12,\n" +
	"\x12gpu_vram_supported\x18\r \x01(\bR\x10gpuVramSupported\x12,\n" +
	"\x12gpu_freq_supported\x18\x0e \x01(\bR\x10gpuFreqSupported\x12.\n" +
	"\x13gpu_power_supported\x18\x0f \x01(\bR\x11gpuPowerSupported\x125\n" +
	"\x17gpu_vram_temp_supported\x18\x10 \x01(\bR\x14gpuVramTempSupported\x125\n" +
	"\x17gpu_vram_freq_supported\x18\x11 \x01(\bR\x14gpuVramFreqSupported\x125\n" +
	"\x17gpu_temp_tmax_supported\x18\x12 \x01(\bR\x14gpuTempTmaxSupported\x12#\n" +
	"\rosd_supported\x18\x13 \x01(\bR\fosdSupported\x123\n" +
	"\x15peripherals_supported\x18\x14 \x01(\bR\x14peripheralsSupported\x12:\n" +
	"\x19package_updates_supported\x18\x15 \x01(\bR\x17packageUpdatesSupported\"\x98\x02\n" +
	"\x10TelemetryPayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\"\n" +
	"\x03cpu\x18\x02 \x01(\v2\x10.pcd.v1.CPUUsageR\x03cpu\x12\"\n" +
	"\x03gpu\x18\x03 \x01(\v2\x10.pcd.v1.GPUUsageR\x03gpu\x12\"\n" +
	"\x03ram\x18\x04 \x01(\v2\x10.pcd.v1.RAMUsageR\x03ram\x12%\n" +
	"\x04swap\x18\x05 \x01(\v2\x11.pcd.v1.SwapUsageR\x04swap\x12%\n" +
	"\x04zram\x18\x06 \x01(\v2\x11.pcd.v1.ZRAMUsageR\x04zram\x12,\n" +
	"\x05flags\x18\a \x01(\v2\x16.pcd.v1.TelemetryFlagsR\x05flags\"9\n" +
	"\x16StreamTelemetryRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\"M\n" +
	"\x17StreamTelemetryResponse\x122\n" +
	"\apayload\x18\x01 \x01(\v2\x18.pcd.v1.TelemetryPayloadR\apayload2h\n" +
	"\x10TelemetryService\x12T\n" +
	"\x0fStreamTelemetry\x12\x1e.pcd.v1.StreamTelemetryRequest\x1a\x1f.pcd.v1.StreamTelemetryResponse0\x01B<Z:github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1;pcdv1b\x06proto3"

var (
	file_pcd_v1_telemetry_proto_rawDescOnce sync.Once
	file_pcd_v1_telemetry_proto_rawDescData []byte
)

func file_pcd_v1_telemetry_proto_rawDescGZIP() []byte {
	file_pcd_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_pcd_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcd_v1_telemetry_proto_rawDesc), len(file_pcd_v1_telemetry_proto_rawDesc)))
	})
	return file_pcd_v1_telemetry_proto_rawDescData
}

var file_pcd_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pcd_v1_telemetry_proto_goTypes = []any{
	(*CPUUsage)(nil),                // 0: pcd.v1.CPUUsage
	(*GPUUsage)(nil),                // 1: pcd.v1.GPUUsage
	(*RAMUsage)(nil),                // 2: pcd.v1.RAMUsage
	(*SwapUsage)(nil),               // 3: pcd.v1.SwapUsage
	(*ZRAMUsage)(nil),               // 4: pcd.v1.ZRAMUsage
	(*TelemetryFlags)(nil),          // 5: pcd.v1.TelemetryFlags
	(*TelemetryPayload)(nil),        // 6: pcd.v1.TelemetryPayload
	(*StreamTelemetryRequest)(nil),  // 7: pcd.v1.StreamTelemetryRequest
	(*StreamTelemetryResponse)(nil), // 8: pcd.v1.StreamTelemetryResponse
}
var file_pcd_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: pcd.v1.TelemetryPayload.cpu:type_name -> pcd.v1.CPUUsage
	1, // 1: pcd.v1.TelemetryPayload.gpu:type_name -> pcd.v1.GPUUsage
	2, // 2: pcd.v1.TelemetryPayload.ram:type_name -> pcd.v1.RAMUsage
	3, // 3: pcd.v1.TelemetryPayload.swap:type_name -> pcd.v1.SwapUsage
	4, // 4: pcd.v1.TelemetryPayload.zram:type_name -> pcd.v1.ZRAMUsage
	5, // 5: pcd.v1.TelemetryPayload.flags:type_name -> pcd.v1.TelemetryFlags
	6, // 6: pcd.v1.StreamTelemetryResponse.payload:type_name -> pcd.v1.TelemetryPayload
	7, // 7: pcd.v1.TelemetryService.StreamTelemetry:input_type -> pcd.v1.StreamTelemetryRequest
	8, // 8: pcd.v1.TelemetryService.StreamTelemetry:output_type -> pcd.v1.StreamTelemetryResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pcd_v1_telemetry_proto_init() }
func file_pcd_v1_telemetry_proto_init() {
	if File_pcd_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcd_v1_telemetry_proto_rawDesc), len(file_pcd_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcd_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_pcd_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_pcd_v1_telemetry_proto_msgTypes,
	}.Build()
	File_pcd_v1_telemetry_proto = out.File
	file_pcd_v1_telemetry_proto_goTypes = nil
	file_pcd_v1_telemetry_proto_depIdxs = nil
}
