// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pcd/v1/bluetooth.proto

package pcdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BluetoothServiceName is the fully-qualified name of the BluetoothService service.
	BluetoothServiceName = "pcd.v1.BluetoothService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BluetoothServiceStreamBluetoothStateProcedure is the fully-qualified name of the
	// BluetoothService's StreamBluetoothState RPC.
	BluetoothServiceStreamBluetoothStateProcedure = "/pcd.v1.BluetoothService/StreamBluetoothState"
)

// BluetoothServiceClient is a client for the pcd.v1.BluetoothService service.
type BluetoothServiceClient interface {
	StreamBluetoothState(context.Context, *connect.Request[v1.StreamBluetoothStateRequest]) (*connect.ServerStreamForClient[v1.StreamBluetoothStateResponse], error)
}

// NewBluetoothServiceClient constructs a client for the pcd.v1.BluetoothService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBluetoothServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BluetoothServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bluetoothServiceMethods := v1.File_pcd_v1_bluetooth_proto.Services().ByName("BluetoothService").Methods()
	return &bluetoothServiceClient{
		streamBluetoothState: connect.NewClient[v1.StreamBluetoothStateRequest, v1.StreamBluetoothStateResponse](
			httpClient,
			baseURL+BluetoothServiceStreamBluetoothStateProcedure,
			connect.WithSchema(bluetoothServiceMethods.ByName("StreamBluetoothState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bluetoothServiceClient implements BluetoothServiceClient.
type bluetoothServiceClient struct {
	streamBluetoothState *connect.Client[v1.StreamBluetoothStateRequest, v1.StreamBluetoothStateResponse]
}

// StreamBluetoothState calls pcd.v1.BluetoothService.StreamBluetoothState.
func (c *bluetoothServiceClient) StreamBluetoothState(ctx context.Context, req *connect.Request[v1.StreamBluetoothStateRequest]) (*connect.ServerStreamForClient[v1.StreamBluetoothStateResponse], error) {
	return c.streamBluetoothState.CallServerStream(ctx, req)
}

// BluetoothServiceHandler is an implementation of the pcd.v1.BluetoothService service.
type BluetoothServiceHandler interface {
	StreamBluetoothState(context.Context, *connect.Request[v1.StreamBluetoothStateRequest], *connect.ServerStream[v1.StreamBluetoothStateResponse]) error
}

// NewBluetoothServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBluetoothServiceHandler(svc BluetoothServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bluetoothServiceMethods := v1.File_pcd_v1_bluetooth_proto.Services().ByName("BluetoothService").Methods()
	bluetoothServiceStreamBluetoothStateHandler := connect.NewServerStreamHandler(
		BluetoothServiceStreamBluetoothStateProcedure,
		svc.StreamBluetoothState,
		connect.WithSchema(bluetoothServiceMethods.ByName("StreamBluetoothState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pcd.v1.BluetoothService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BluetoothServiceStreamBluetoothStateProcedure:
			bluetoothServiceStreamBluetoothStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBluetoothServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBluetoothServiceHandler struct{}

func (UnimplementedBluetoothServiceHandler) StreamBluetoothState(context.Context, *connect.Request[v1.StreamBluetoothStateRequest], *connect.ServerStream[v1.StreamBluetoothStateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.BluetoothService.StreamBluetoothState is not implemented"))
}
