// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pcd/v1/media.proto

package pcdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MediaServiceName is the fully-qualified name of the MediaService service.
	MediaServiceName = "pcd.v1.MediaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MediaServiceStreamMediaStateProcedure is the fully-qualified name of the MediaService's
	// StreamMediaState RPC.
	MediaServiceStreamMediaStateProcedure = "/pcd.v1.MediaService/StreamMediaState"
	// MediaServiceSendMediaCommandProcedure is the fully-qualified name of the MediaService's
	// SendMediaCommand RPC.
	MediaServiceSendMediaCommandProcedure = "/pcd.v1.MediaService/SendMediaCommand"
)

// MediaServiceClient is a client for the pcd.v1.MediaService service.
type MediaServiceClient interface {
	StreamMediaState(context.Context, *connect.Request[v1.StreamMediaStateRequest]) (*connect.ServerStreamForClient[v1.StreamMediaStateResponse], error)
	SendMediaCommand(context.Context, *connect.Request[v1.SendMediaCommandRequest]) (*connect.Response[v1.SendMediaCommandResponse], error)
}

// NewMediaServiceClient constructs a client for the pcd.v1.MediaService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMediaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MediaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mediaServiceMethods := v1.File_pcd_v1_media_proto.Services().ByName("MediaService").Methods()
	return &mediaServiceClient{
		streamMediaState: connect.NewClient[v1.StreamMediaStateRequest, v1.StreamMediaStateResponse](
			httpClient,
			baseURL+MediaServiceStreamMediaStateProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("StreamMediaState")),
			connect.WithClientOptions(opts...),
		),
		sendMediaCommand: connect.NewClient[v1.SendMediaCommandRequest, v1.SendMediaCommandResponse](
			httpClient,
			baseURL+MediaServiceSendMediaCommandProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("SendMediaCommand")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mediaServiceClient implements MediaServiceClient.
type mediaServiceClient struct {
	streamMediaState *connect.Client[v1.StreamMediaStateRequest, v1.StreamMediaStateResponse]
	sendMediaCommand *connect.Client[v1.SendMediaCommandRequest, v1.SendMediaCommandResponse]
}

// StreamMediaState calls pcd.v1.MediaService.StreamMediaState.
func (c *mediaServiceClient) StreamMediaState(ctx context.Context, req *connect.Request[v1.StreamMediaStateRequest]) (*connect.ServerStreamForClient[v1.StreamMediaStateResponse], error) {
	return c.streamMediaState.CallServerStream(ctx, req)
}

// SendMediaCommand calls pcd.v1.MediaService.SendMediaCommand.
func (c *mediaServiceClient) SendMediaCommand(ctx context.Context, req *connect.Request[v1.SendMediaCommandRequest]) (*connect.Response[v1.SendMediaCommandResponse], error) {
	return c.sendMediaCommand.CallUnary(ctx, req)
}

// MediaServiceHandler is an implementation of the pcd.v1.MediaService service.
type MediaServiceHandler interface {
	StreamMediaState(context.Context, *connect.Request[v1.StreamMediaStateRequest], *connect.ServerStream[v1.StreamMediaStateResponse]) error
	SendMediaCommand(context.Context, *connect.Request[v1.SendMediaCommandRequest]) (*connect.Response[v1.SendMediaCommandResponse], error)
}

// NewMediaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMediaServiceHandler(svc MediaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mediaServiceMethods := v1.File_pcd_v1_media_proto.Services().ByName("MediaService").Methods()
	mediaServiceStreamMediaStateHandler := connect.NewServerStreamHandler(
		MediaServiceStreamMediaStateProcedure,
		svc.StreamMediaState,
		connect.WithSchema(mediaServiceMethods.ByName("StreamMediaState")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceSendMediaCommandHandler := connect.NewUnaryHandler(
		MediaServiceSendMediaCommandProcedure,
		svc.SendMediaCommand,
		connect.WithSchema(mediaServiceMethods.ByName("SendMediaCommand")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pcd.v1.MediaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MediaServiceStreamMediaStateProcedure:
			mediaServiceStreamMediaStateHandler.ServeHTTP(w, r)
		case MediaServiceSendMediaCommandProcedure:
			mediaServiceSendMediaCommandHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMediaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMediaServiceHandler struct{}

func (UnimplementedMediaServiceHandler) StreamMediaState(context.Context, *connect.Request[v1.StreamMediaStateRequest], *connect.ServerStream[v1.StreamMediaStateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.MediaService.StreamMediaState is not implemented"))
}

func (UnimplementedMediaServiceHandler) SendMediaCommand(context.Context, *connect.Request[v1.SendMediaCommandRequest]) (*connect.Response[v1.SendMediaCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.MediaService.SendMediaCommand is not implemented"))
}
