// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pcd/v1/notification.proto

package pcdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "pcd.v1.NotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationServiceStreamNotificationsProcedure is the fully-qualified name of the
	// NotificationService's StreamNotifications RPC.
	NotificationServiceStreamNotificationsProcedure = "/pcd.v1.NotificationService/StreamNotifications"
	// NotificationServiceSendNotificationProcedure is the fully-qualified name of the
	// NotificationService's SendNotification RPC.
	NotificationServiceSendNotificationProcedure = "/pcd.v1.NotificationService/SendNotification"
	// NotificationServiceTriggerNotificationActionProcedure is the fully-qualified name of the
	// NotificationService's TriggerNotificationAction RPC.
	NotificationServiceTriggerNotificationActionProcedure = "/pcd.v1.NotificationService/TriggerNotificationAction"
	// NotificationServiceDismissNotificationProcedure is the fully-qualified name of the
	// NotificationService's DismissNotification RPC.
	NotificationServiceDismissNotificationProcedure = "/pcd.v1.NotificationService/DismissNotification"
)

// NotificationServiceClient is a client for the pcd.v1.NotificationService service.
type NotificationServiceClient interface {
	StreamNotifications(context.Context, *connect.Request[v1.StreamNotificationsRequest]) (*connect.ServerStreamForClient[v1.StreamNotificationsResponse], error)
	SendNotification(context.Context, *connect.Request[v1.SendNotificationRequest]) (*connect.Response[v1.SendNotificationResponse], error)
	TriggerNotificationAction(context.Context, *connect.Request[v1.TriggerNotificationActionRequest]) (*connect.Response[v1.TriggerNotificationActionResponse], error)
	DismissNotification(context.Context, *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error)
}

// NewNotificationServiceClient constructs a client for the pcd.v1.NotificationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationServiceMethods := v1.File_pcd_v1_notification_proto.Services().ByName("NotificationService").Methods()
	return &notificationServiceClient{
		streamNotifications: connect.NewClient[v1.StreamNotificationsRequest, v1.StreamNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceStreamNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("StreamNotifications")),
			connect.WithClientOptions(opts...),
		),
		sendNotification: connect.NewClient[v1.SendNotificationRequest, v1.SendNotificationResponse](
			httpClient,
			baseURL+NotificationServiceSendNotificationProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("SendNotification")),
			connect.WithClientOptions(opts...),
		),
		triggerNotificationAction: connect.NewClient[v1.TriggerNotificationActionRequest, v1.TriggerNotificationActionResponse](
			httpClient,
			baseURL+NotificationServiceTriggerNotificationActionProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("TriggerNotificationAction")),
			connect.WithClientOptions(opts...),
		),
		dismissNotification: connect.NewClient[v1.DismissNotificationRequest, v1.DismissNotificationResponse](
			httpClient,
			baseURL+NotificationServiceDismissNotificationProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("DismissNotification")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	streamNotifications       *connect.Client[v1.StreamNotificationsRequest, v1.StreamNotificationsResponse]
	sendNotification          *connect.Client[v1.SendNotificationRequest, v1.SendNotificationResponse]
	triggerNotificationAction *connect.Client[v1.TriggerNotificationActionRequest, v1.TriggerNotificationActionResponse]
	dismissNotification       *connect.Client[v1.DismissNotificationRequest, v1.DismissNotificationResponse]
}

// StreamNotifications calls pcd.v1.NotificationService.StreamNotifications.
func (c *notificationServiceClient) StreamNotifications(ctx context.Context, req *connect.Request[v1.StreamNotificationsRequest]) (*connect.ServerStreamForClient[v1.StreamNotificationsResponse], error) {
	return c.streamNotifications.CallServerStream(ctx, req)
}

// SendNotification calls pcd.v1.NotificationService.SendNotification.
func (c *notificationServiceClient) SendNotification(ctx context.Context, req *connect.Request[v1.SendNotificationRequest]) (*connect.Response[v1.SendNotificationResponse], error) {
	return c.sendNotification.CallUnary(ctx, req)
}

// TriggerNotificationAction calls pcd.v1.NotificationService.TriggerNotificationAction.
func (c *notificationServiceClient) TriggerNotificationAction(ctx context.Context, req *connect.Request[v1.TriggerNotificationActionRequest]) (*connect.Response[v1.TriggerNotificationActionResponse], error) {
	return c.triggerNotificationAction.CallUnary(ctx, req)
}

// DismissNotification calls pcd.v1.NotificationService.DismissNotification.
func (c *notificationServiceClient) DismissNotification(ctx context.Context, req *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error) {
	return c.dismissNotification.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the pcd.v1.NotificationService service.
type NotificationServiceHandler interface {
	StreamNotifications(context.Context, *connect.Request[v1.StreamNotificationsRequest], *connect.ServerStream[v1.StreamNotificationsResponse]) error
	SendNotification(context.Context, *connect.Request[v1.SendNotificationRequest]) (*connect.Response[v1.SendNotificationResponse], error)
	TriggerNotificationAction(context.Context, *connect.Request[v1.TriggerNotificationActionRequest]) (*connect.Response[v1.TriggerNotificationActionResponse], error)
	DismissNotification(context.Context, *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceMethods := v1.File_pcd_v1_notification_proto.Services().ByName("NotificationService").Methods()
	notificationServiceStreamNotificationsHandler := connect.NewServerStreamHandler(
		NotificationServiceStreamNotificationsProcedure,
		svc.StreamNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("StreamNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceSendNotificationHandler := connect.NewUnaryHandler(
		NotificationServiceSendNotificationProcedure,
		svc.SendNotification,
		connect.WithSchema(notificationServiceMethods.ByName("SendNotification")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceTriggerNotificationActionHandler := connect.NewUnaryHandler(
		NotificationServiceTriggerNotificationActionProcedure,
		svc.TriggerNotificationAction,
		connect.WithSchema(notificationServiceMethods.ByName("TriggerNotificationAction")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceDismissNotificationHandler := connect.NewUnaryHandler(
		NotificationServiceDismissNotificationProcedure,
		svc.DismissNotification,
		connect.WithSchema(notificationServiceMethods.ByName("DismissNotification")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pcd.v1.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceStreamNotificationsProcedure:
			notificationServiceStreamNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceSendNotificationProcedure:
			notificationServiceSendNotificationHandler.ServeHTTP(w, r)
		case NotificationServiceTriggerNotificationActionProcedure:
			notificationServiceTriggerNotificationActionHandler.ServeHTTP(w, r)
		case NotificationServiceDismissNotificationProcedure:
			notificationServiceDismissNotificationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) StreamNotifications(context.Context, *connect.Request[v1.StreamNotificationsRequest], *connect.ServerStream[v1.StreamNotificationsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.NotificationService.StreamNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) SendNotification(context.Context, *connect.Request[v1.SendNotificationRequest]) (*connect.Response[v1.SendNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.NotificationService.SendNotification is not implemented"))
}

func (UnimplementedNotificationServiceHandler) TriggerNotificationAction(context.Context, *connect.Request[v1.TriggerNotificationActionRequest]) (*connect.Response[v1.TriggerNotificationActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.NotificationService.TriggerNotificationAction is not implemented"))
}

func (UnimplementedNotificationServiceHandler) DismissNotification(context.Context, *connect.Request[v1.DismissNotificationRequest]) (*connect.Response[v1.DismissNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.NotificationService.DismissNotification is not implemented"))
}
