// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pcd/v1/system.proto

package pcdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SystemServiceName is the fully-qualified name of the SystemService service.
	SystemServiceName = "pcd.v1.SystemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SystemServiceStreamSystemStateProcedure is the fully-qualified name of the SystemService's
	// StreamSystemState RPC.
	SystemServiceStreamSystemStateProcedure = "/pcd.v1.SystemService/StreamSystemState"
	// SystemServiceExecuteSystemActionProcedure is the fully-qualified name of the SystemService's
	// ExecuteSystemAction RPC.
	SystemServiceExecuteSystemActionProcedure = "/pcd.v1.SystemService/ExecuteSystemAction"
	// SystemServiceSetPowerProfileProcedure is the fully-qualified name of the SystemService's
	// SetPowerProfile RPC.
	SystemServiceSetPowerProfileProcedure = "/pcd.v1.SystemService/SetPowerProfile"
)

// SystemServiceClient is a client for the pcd.v1.SystemService service.
type SystemServiceClient interface {
	StreamSystemState(context.Context, *connect.Request[v1.StreamSystemStateRequest]) (*connect.ServerStreamForClient[v1.StreamSystemStateResponse], error)
	ExecuteSystemAction(context.Context, *connect.Request[v1.ExecuteSystemActionRequest]) (*connect.Response[v1.ExecuteSystemActionResponse], error)
	SetPowerProfile(context.Context, *connect.Request[v1.SetPowerProfileRequest]) (*connect.Response[v1.SetPowerProfileResponse], error)
}

// NewSystemServiceClient constructs a client for the pcd.v1.SystemService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	systemServiceMethods := v1.File_pcd_v1_system_proto.Services().ByName("SystemService").Methods()
	return &systemServiceClient{
		streamSystemState: connect.NewClient[v1.StreamSystemStateRequest, v1.StreamSystemStateResponse](
			httpClient,
			baseURL+SystemServiceStreamSystemStateProcedure,
			connect.WithSchema(systemServiceMethods.ByName("StreamSystemState")),
			connect.WithClientOptions(opts...),
		),
		executeSystemAction: connect.NewClient[v1.ExecuteSystemActionRequest, v1.ExecuteSystemActionResponse](
			httpClient,
			baseURL+SystemServiceExecuteSystemActionProcedure,
			connect.WithSchema(systemServiceMethods.ByName("ExecuteSystemAction")),
			connect.WithClientOptions(opts...),
		),
		setPowerProfile: connect.NewClient[v1.SetPowerProfileRequest, v1.SetPowerProfileResponse](
			httpClient,
			baseURL+SystemServiceSetPowerProfileProcedure,
			connect.WithSchema(systemServiceMethods.ByName("SetPowerProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// systemServiceClient implements SystemServiceClient.
type systemServiceClient struct {
	streamSystemState   *connect.Client[v1.StreamSystemStateRequest, v1.StreamSystemStateResponse]
	executeSystemAction *connect.Client[v1.ExecuteSystemActionRequest, v1.ExecuteSystemActionResponse]
	setPowerProfile     *connect.Client[v1.SetPowerProfileRequest, v1.SetPowerProfileResponse]
}

// StreamSystemState calls pcd.v1.SystemService.StreamSystemState.
func (c *systemServiceClient) StreamSystemState(ctx context.Context, req *connect.Request[v1.StreamSystemStateRequest]) (*connect.ServerStreamForClient[v1.StreamSystemStateResponse], error) {
	return c.streamSystemState.CallServerStream(ctx, req)
}

// ExecuteSystemAction calls pcd.v1.SystemService.ExecuteSystemAction.
func (c *systemServiceClient) ExecuteSystemAction(ctx context.Context, req *connect.Request[v1.ExecuteSystemActionRequest]) (*connect.Response[v1.ExecuteSystemActionResponse], error) {
	return c.executeSystemAction.CallUnary(ctx, req)
}

// SetPowerProfile calls pcd.v1.SystemService.SetPowerProfile.
func (c *systemServiceClient) SetPowerProfile(ctx context.Context, req *connect.Request[v1.SetPowerProfileRequest]) (*connect.Response[v1.SetPowerProfileResponse], error) {
	return c.setPowerProfile.CallUnary(ctx, req)
}

// SystemServiceHandler is an implementation of the pcd.v1.SystemService service.
type SystemServiceHandler interface {
	StreamSystemState(context.Context, *connect.Request[v1.StreamSystemStateRequest], *connect.ServerStream[v1.StreamSystemStateResponse]) error
	ExecuteSystemAction(context.Context, *connect.Request[v1.ExecuteSystemActionRequest]) (*connect.Response[v1.ExecuteSystemActionResponse], error)
	SetPowerProfile(context.Context, *connect.Request[v1.SetPowerProfileRequest]) (*connect.Response[v1.SetPowerProfileResponse], error)
}

// NewSystemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSystemServiceHandler(svc SystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	systemServiceMethods := v1.File_pcd_v1_system_proto.Services().ByName("SystemService").Methods()
	systemServiceStreamSystemStateHandler := connect.NewServerStreamHandler(
		SystemServiceStreamSystemStateProcedure,
		svc.StreamSystemState,
		connect.WithSchema(systemServiceMethods.ByName("StreamSystemState")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceExecuteSystemActionHandler := connect.NewUnaryHandler(
		SystemServiceExecuteSystemActionProcedure,
		svc.ExecuteSystemAction,
		connect.WithSchema(systemServiceMethods.ByName("ExecuteSystemAction")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceSetPowerProfileHandler := connect.NewUnaryHandler(
		SystemServiceSetPowerProfileProcedure,
		svc.SetPowerProfile,
		connect.WithSchema(systemServiceMethods.ByName("SetPowerProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pcd.v1.SystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SystemServiceStreamSystemStateProcedure:
			systemServiceStreamSystemStateHandler.ServeHTTP(w, r)
		case SystemServiceExecuteSystemActionProcedure:
			systemServiceExecuteSystemActionHandler.ServeHTTP(w, r)
		case SystemServiceSetPowerProfileProcedure:
			systemServiceSetPowerProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSystemServiceHandler struct{}

func (UnimplementedSystemServiceHandler) StreamSystemState(context.Context, *connect.Request[v1.StreamSystemStateRequest], *connect.ServerStream[v1.StreamSystemStateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.SystemService.StreamSystemState is not implemented"))
}

func (UnimplementedSystemServiceHandler) ExecuteSystemAction(context.Context, *connect.Request[v1.ExecuteSystemActionRequest]) (*connect.Response[v1.ExecuteSystemActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.SystemService.ExecuteSystemAction is not implemented"))
}

func (UnimplementedSystemServiceHandler) SetPowerProfile(context.Context, *connect.Request[v1.SetPowerProfileRequest]) (*connect.Response[v1.SetPowerProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.SystemService.SetPowerProfile is not implemented"))
}
