// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pcd/v1/telemetry.proto

package pcdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/noosxe/pc-dashboard-server/pkg/api/pcd/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryServiceName is the fully-qualified name of the TelemetryService service.
	TelemetryServiceName = "pcd.v1.TelemetryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryServiceStreamTelemetryProcedure is the fully-qualified name of the TelemetryService's
	// StreamTelemetry RPC.
	TelemetryServiceStreamTelemetryProcedure = "/pcd.v1.TelemetryService/StreamTelemetry"
)

// TelemetryServiceClient is a client for the pcd.v1.TelemetryService service.
type TelemetryServiceClient interface {
	StreamTelemetry(context.Context, *connect.Request[v1.StreamTelemetryRequest]) (*connect.ServerStreamForClient[v1.StreamTelemetryResponse], error)
}

// NewTelemetryServiceClient constructs a client for the pcd.v1.TelemetryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryServiceMethods := v1.File_pcd_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	return &telemetryServiceClient{
		streamTelemetry: connect.NewClient[v1.StreamTelemetryRequest, v1.StreamTelemetryResponse](
			httpClient,
			baseURL+TelemetryServiceStreamTelemetryProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("StreamTelemetry")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryServiceClient implements TelemetryServiceClient.
type telemetryServiceClient struct {
	streamTelemetry *connect.Client[v1.StreamTelemetryRequest, v1.StreamTelemetryResponse]
}

// StreamTelemetry calls pcd.v1.TelemetryService.StreamTelemetry.
func (c *telemetryServiceClient) StreamTelemetry(ctx context.Context, req *connect.Request[v1.StreamTelemetryRequest]) (*connect.ServerStreamForClient[v1.StreamTelemetryResponse], error) {
	return c.streamTelemetry.CallServerStream(ctx, req)
}

// TelemetryServiceHandler is an implementation of the pcd.v1.TelemetryService service.
type TelemetryServiceHandler interface {
	StreamTelemetry(context.Context, *connect.Request[v1.StreamTelemetryRequest], *connect.ServerStream[v1.StreamTelemetryResponse]) error
}

// NewTelemetryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryServiceHandler(svc TelemetryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryServiceMethods := v1.File_pcd_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	telemetryServiceStreamTelemetryHandler := connect.NewServerStreamHandler(
		TelemetryServiceStreamTelemetryProcedure,
		svc.StreamTelemetry,
		connect.WithSchema(telemetryServiceMethods.ByName("StreamTelemetry")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pcd.v1.TelemetryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryServiceStreamTelemetryProcedure:
			telemetryServiceStreamTelemetryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryServiceHandler struct{}

func (UnimplementedTelemetryServiceHandler) StreamTelemetry(context.Context, *connect.Request[v1.StreamTelemetryRequest], *connect.ServerStream[v1.StreamTelemetryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pcd.v1.TelemetryService.StreamTelemetry is not implemented"))
}
